### PR TITLE
Minor changes.

### PR DESCRIPTION
**Pull request by deanwampler**
1. Enabled scrolling for pip install cell output. 
2. Deleted a duplicate "has" in a print statement.

### CODE REVIEW

**Review by adampingel — APPROVED** [review]

**Comment by fayvor** [comment]
@deanwampler is it possible to set the output of a cell to scroll by default? I don't see that in this PR.

**Comment by deanwampler** [comment]
Hmm. You are right. I did turn it on. It looks like the setting was removed some how(?). I wonder if this happened when I cleared output? Anyway, this delta should be there:

```
@ recipes/Summarize/Summarize.ipynb:29 @
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
<    "id": "2zUHQD71qgqf"
>    "id": "2zUHQD71qgqf",
>    "scrolled": true
   },
   "outputs": [],
   "source": [
```

So, you can see how you could add this setting manually 😁 . I'll create a new PR for this change.

**Comment by deanwampler** [comment]
For completeness, clearing the output in Jupyter itself, doesn't reset the flag. It appears the `nbstripout` hook does reset it.

**Comment by fayvor** [comment]
Looks like `nbstripout` can be configured to preserve the `scrolled`
setting with:
`--keep-metadata-keys="cell.metadata.collapsed cell.metadata.scrolled"`

https://github.com/kynan/nbstripout?tab=readme-ov-file#stripping-metadata

**Comment by fayvor** [comment]
Looks like `nbstripout` can be configured to preserve the `scrolled` setting with:
`--keep-metadata-keys="cell.metadata.collapsed cell.metadata.scrolled"`

https://github.com/kynan/nbstripout?tab=readme-ov-file#stripping-metadata

**Comment by deanwampler** [comment]
Oh great!

**Pull request merged**
