### PR TITLE
Add granite guardian examples using watsonx

### PR DESCRIPTION
**Pull request by martinscooper**
### Model Interaction

- [ ] **Flexible LLM platform support** The platform should be easily switchable. Use LangChain or LlamaIndex.
- [x] **Use prompt guide corresponding to the model**  For example for [Granite 3.x Language Models](https://www.ibm.com/granite/docs/models/granite/#prompt-anatomy)

### Data

- [ ] **Example data**: Follow the example data guidance.

### Notebook requirements

- [x] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [x] **Automated testing**: Add the recipe to the automated tests as described [here](https://github.com/ibm-granite-community/community/wiki/Automated-Validation)
- [x] **Test in Google Colab**:
    - [x] Test that it works in Google Colab (Python 3.10.12).
    - [x] Colab has its own package set and Python version, so ensure compatibility.
- [x] **Test locally**:
    - [x] Ensure the code works in a fresh Python virtual environment (venv).
- [x] **Standard access to secrets and variables** Include `!pip install git+https://github.com/ibm-granite-community/utils` in the first code cell in order to make `get_env_var` available to accessing secrets and variables in the recipe.

### Incoming References

- [x] **README.md updates**:
    - [x] Add a link to the recipe in the Table of Contents (ToC).
    - [x] Include a Colab button after that link.

### GitHub

- [x] **Commits signed**: All commits must be GPG or SSH signed.
- [x] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.

### CODE REVIEW

**Comment by adampingel** [comment]
Hi, @martinscooper .  Please have a look at the checklist for recipes: https://github.com/ibm-granite-community/community/wiki/Authoring-Recipes

**Comment by martinscooper** [comment]
@adampingel Done!

**Comment by martinscooper** [comment]
@adampingel I resolved the conflicts.

**Comment by martinscooper** [comment]
@adampingel Hi! is there any reason this is not being merged? If so, let me know.

**Comment by bjhargrave** [comment]
There are new merge conflicts as we replaced the vanilla workflow yaml. You now only need to add the new notebook to the txt file.

**Comment by adampingel** [comment]
@martinscooper The test is failing: https://github.com/ibm-granite-community/granite-snack-cookbook/actions/runs/12054219413/job/33611754118?pr=51

Please follow the established pattern using the `get_env_var` from the `utils` repo.

A example of that applied to WatsonX can be found here: https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb

**Pull request closed without merging**
